-- ==============================================================================
-- 1. PROFILES TABLE (Required for Authentication & My Lab)
-- ==============================================================================

-- Create a table for public profiles linked to auth.users
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  name text,
  email text,
  avatar_url text,
  phone text,
  address text,
  loyalty_points integer default 0
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." 
  on public.profiles for select using (true);

create policy "Users can insert their own profile." 
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update their own profile." 
  on public.profiles for update using (auth.uid() = id);


-- ==============================================================================
-- 2. MENU TABLES (Optional: For dynamic menu data)
-- ==============================================================================

-- Categories Table
create table if not exists public.categories (
  id text primary key, -- e.g., 'burgers', 'sandwiches'
  title text not null,
  note text,
  sort_order integer generated by default as identity
);

-- Menu Items Table
create table if not exists public.menu_items (
  id text primary key, -- e.g., 'b1', 'b2'
  category_id text references public.categories(id),
  name text not null,
  description text,
  price text not null, -- Using text to support simple prices or variants like "250 / 270"
  type text not null check (type in ('veg', 'non-veg', 'both')), 
  icons text[], -- Array of strings e.g. ['wheat', 'dairy']
  is_new boolean default false,
  sort_order integer generated by default as identity
);

-- Enable RLS for Menu
alter table public.categories enable row level security;
alter table public.menu_items enable row level security;

-- Allow read access to everyone
create policy "Allow public read access categories" on public.categories for select using (true);
create policy "Allow public read access menu_items" on public.menu_items for select using (true);


-- ==============================================================================
-- 3. ORDERS TABLE (Optional: To store online orders)
-- ==============================================================================

create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  user_id uuid references auth.users(id), -- Nullable for guest checkout
  guest_info jsonb, -- JSON object for { name, phone, address } if guest
  items jsonb not null, -- JSON array storing the cart items snapshot
  total_amount numeric not null,
  status text default 'pending' -- 'pending', 'confirmed', 'delivered'
);

alter table public.orders enable row level security;

-- Policies for Orders
create policy "Users can view their own orders" 
  on public.orders for select using (auth.uid() = user_id);

create policy "Anyone can create orders" 
  on public.orders for insert with check (true);
